---
# This task report external libraries installed on the gateway.
- name: List external libraries
  find:
    paths: "{{ gateway_external_libs_dir }}"
  register: report_external_libs
  ignore_errors: True
