---
# This task report mysql8 compatibility checker.
# Uncomment
- name: Grant gateway all privileges to database
  shell:
   cmd: mysql -u{{ database_admin_user }}  -p{{ database_admin_pass }} -e "GRANT ALL PRIVILEGES ON *.* TO '{{ database_user }}'@'%'; flush privileges;"
  no_log: "{{ no_log }}"
  when: inventory_hostname in groups['gateway_mysql']

- name: Run Mysql8 Compatibility Checker
  shell:
    cmd: mysqlsh {{ database_user }}:{{ database_pass }}@{{ inventory_hostname }}:{{ database_port }} -e "util.checkForServerUpgrade();"
  no_log: "{{ no_log }}"
  ignore_errors: True
  register: report_mysql8_compatibility_check
  delegate_to: localhost
  when: inventory_hostname in groups['gateway_mysql']