---
- name: Download pip
  command: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  register: status
  changed_when: status.rc == 0

- name: Install pip
  command: python get-pip.py
  register: status
  changed_when: status.rc == 0

- name: Install pexpect
  command: pip install pexpect
  register: status
  changed_when: status.rc == 0

- name: Checking that pexpect is usable
  shell:
    cmd: (echo import pexpect;) | /usr/bin/python
  changed_when: False
